supabase/supautils

src/supautils.c
Hi!
I refactored src/supautils.c. Specifically, I removed whitespaces, adjusted line breaks, and changed the comment format (for consistency, the use of "//" is not recommended in PostgreSQL. [1]).
[1] https://www.postgresql.org/docs/devel/source-format.html
Regards,
Shinya Kato
=> Clean whitecpace, coment formatting, and line feed position.

src/supautils.c, test/expected/restricted_placeholders.out, test/sql/restricted_placeholders.sql
Fixes https://github.com/supabase/supautils/issues/24.
=> fix: don't crash after a show all

.github/workflows/main.yml, shell.nix, src/privileged_extensions.c
Fixes https://github.com/supabase/supautils/issues/31
=> compatibility with pg 15

src/supautils.c, test/expected/privileged_role.out, test/sql/privileged_role.sql
Closes https://github.com/supabase/supautils/issues/34
=> fix: only run deferred bypassrls if clause is supplied

src/privileged_extensions.c, src/privileged_extensions.h, src/supautils.c, src/utils.c, src/utils.h
Clean up privileged extensions code - easier to review per commit.
=> refactor privileged extensions code

src/privileged_extensions.c, src/supautils.c, test/expected/privileged_extensions.out, test/sql/privileged_extensions.sql
=> feat: run extension custom scripts for superusers as well

.github/workflows/release.yml
tested on https://github.com/soedirgo/supautils/releases/tag/v1.7.11
=> chore(ci): add .deb upload action

.github/workflows/release.yml
Self-hosted runner does not like Nix :(
https://github.com/supabase/supautils/actions/runs/4131259032/jobs/7138732539#step:4:173
=> chore: fix deb upload action failures

src/supautils.c
Fixes https://github.com/supabase/supautils/issues/42
=> fix: handle "" on placeholders_disallowed_values

src/supautils.c
When trying placeholders_disallowed_values, I found the following two issues. Attached patch fixes them. Could you review the patch?
(1)
The error message output by placeholders_disallowed_values always failed to display the disallowed token. For example,
```
=# SHOW supautils.placeholders;
supautils.placeholders 
------------------------
hoge.test
(1 row)
=# SHOW supautils.placeholders_disallowed_values;
supautils.placeholders_disallowed_values 
------------------------------------------
abc
(1 row)
=# SET hoge.test TO 'abc';
ERROR:  The placeholder contains the " disallowed value
```
This issue happend because restrict_placeholders_check_hook() free'd "tofree" variable before reporting the error message even though the message referenced the variable.
(2)
When postgresql.conf contains …
=> Fix bugs in restrict_placeholders_check_hook().

.github/workflows/release.yml
https://github.com/supabase/supautils/actions/runs/5546682818
=> fix: failing release

nix/pg_tle.nix, nix/supautils.nix, nix/withTmpDb.sh.in, src/supautils.c, src/utils.c, src/utils.h, test/expected/privileged_role.out, test/sql/privileged_role.sql
Step towards solving https://github.com/supabase/supautils/issues/79.
=> refactor: remove standard hook from utils.c 

.github/workflows/release.yml
[Context](https://supabase.slack.com/archives/C03JPUSG2FM/p1730265844082659)
=> chore: upload .deb to S3

nix/postgresql/generic.nix, src/constrained_extensions.c, src/supautils.c
Also remove unnecessary top function signatures.
=> refactor: retab supautils/constrained_extensions.c

nix/withTmpDb.sh.in, src/supautils.c, test/expected/linux_constrained_extensions.out
A refactor, plus a test update for [constrained extensions](https://github.com/supabase/supautils?tab=readme-ov-file#constrained-extensions) to pass Github CI since they updated their memory limit.
=> refac: confirm_reserved_roles to is_reserved_role

src/privileged_extensions.c
Uses stack allocation instead of dynamic allocation and makes the code more readable.
=> refactor: run_custom_script SQL template

README.md
Also requires reordering and expanding privileged role docs to explain the whole picture.
[Rendered](https://github.com/steve-chavez/supautils/blob/doc-evtrigs/README.md#non-superuser-event-triggers)
=> docs: non-superuser event triggers

.github/workflows/release.yml
https://github.com/supabase/supautils/actions/runs/13518320428/job/37771687135#step:7:22
=> chore: missing perms in CI

src/event_triggers.c, src/event_triggers.h, src/supautils.c, test/expected/event_triggers.out.in, test/sql/event_triggers.sql
Closes https://github.com/supabase/supautils/issues/140.
=> fix: evtrigs firing security definer functions

Makefile, nix/xpg.nix
Closes https://github.com/supabase/supautils/issues/149
=> fix: compilation with standard PGXS target

.github/workflows/main.yml, nix/xpg.nix, src/pg_prelude.h, src/supautils.c
The `lowerstr` function was removed in favor of `str_tolower`.
=> feat: compatibility with pg 18beta1
