supabase/supautils

.editorconfig
src/supautils.c

Coding style update to match the coding style in core Postgres code.
There's no behaviour change.
There are 3 commits in this pull-request.
The first commit (1a977e6784184da1ed28bf6f0d3ed7ffc2c35575) removes some whitespace and blank lines to match the Postgres coding style, as documented in the community [wiki][] and [docs][]
[wiki]: https://wiki.postgresql.org/wiki/So,_you_want_to_be_a_developer%3F#Style_Guide
[docs]: https://www.postgresql.org/docs/current/source.html
The second commit (63507eae0b3b8be8472b787aba472e709752fbd6) adds `.editorconfig` file at the top-level, to aid the developers and their editors in maintaining this style. This config is copied [verbatim][] from Postgres repository.
[verbatim]: https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=.editorconfig;h=d6 …

Minor changes to match Postgres community coding style 

---

src/supautils.c
test/expected/reserved_roles.out
test/sql/reserved_roles.sql

- Closes #11: Don't use `get_rolespec_name()` on the DROP ROLE case because it validates that the ROLE exists before the standard hook can act and be lenient on DROP ROLE IF EXISTS.
- Closes #10: ALTER TABLE RENAME was failing, only catch ALTER ROLE RENAME statements and avoid processing other RENAME statements.

fix: don't fail on DROP ROLE IF EXISTS/ALTER TABLE RENAME

---

src/supautils.c
test/expected/reserved_memberships.out
test/expected/reserved_roles.out
test/sql/reserved_memberships.sql
test/sql/reserved_roles.sql

I think it is better reserved-role cannot be modified by using grant or revoke.
So I changed source code to that way.
Do you think?

Restrict grant or revoke reserved roles memberships

---

docs/role_security.md

Hi!
I fixed docs to change quotation marks in GUC parameter to single quotes because of occuring error using double quotation.

Fix docs to change quotation marks in GUC parameter to single quotes.

---

src/supautils.c

Hi!
When I executed `make installcheck` with the following settings, the regression test failed.
```
shared_preload_libraries='supautils'
supautils.reserved_roles='aaa'
supautils.reserved_memberships='bbb'
```
The reason is that executing superuser() within an invalid transaction will result in an assertion error.
So, I fixed it.
Regards

Hotfix fail make installcheck

---

src/supautils.c

Hi!
The source code changes discussed in #19 are now complete.
Initially, the flow was going to be as follows.
1. Check valid transaction
2. Check superuser
3. Check utility_stmt->type
4. In case of CREATE ROLE or GRANT, convert GUC to List and execute the main logic
Considering that the DDL command is rarely used, we have changed the flow to the following.
1. Check utility_stmt->type
2. Check valid transaction and check superuser
4. In case of CREATE ROLE or GRANT, convert GUC to List and execute the main logic
All tests passed, but I've changed a lot of code, so there may be some mistakes. Please review it.

Update structure to speed up processing time.

---

src/supautils.c

Hi!
In #20, I seem to have forgotten to include a statement to check if GUCs are set.
If SplitIdentifierString is executed without this statement, a segmentation fault will occur.
I fixed it.
Regards,
Shinya Kato

Add statements for checking if GUCs are set.

---

shell.nix
src/supautils.c
test/expected/restricted_placeholders.out
test/sql/restricted_placeholders.sql

Allow restricting placeholders values used by other services.
In particular, PostgREST can set the [response.headers placeholder](https://postgrest.org/en/stable/api.html#setting-response-headers) to add headers to an HTTP response. Certain headers can be disallowed like:
```sql
supautils.placeholders="response.headers, another.placeholder"
supautils.placeholders_disallowed_values="content-type,cache-control"
SELECT set_config('response.headers',  '{"Content-Type": "application/vnd.my.malicious.type"}]', true);
-- ERROR:  22023: The placeholder contains the "content-type" disallowed value
```
The `placeholders_disallowed_values` will be applied to all `placeholders`. We cannot map different disallowed values to different placeholders due to restrictions in the postgres C API.  The …

Add the ability to restrict placeholders' values

---

.github/workflows/main.yml
Makefile
shell.nix
src/supautils.c
src/utils.c
src/utils.h
test/expected/privileged_role.out
test/fixtures.sql
test/sql/privileged_role.sql

Feature
- cannot `comment` on privileged extensions because they are owned by the `privileged_extensions_superuser`
- cannot set `bypassrls` role attribute without being superuser
- cannot `set session_replication_role` without being superuser
Allow setting a role to be a `privileged_role`, which has additional privileges:
- can `comment` on any extension
- can `{create|alter} role ... [no]bypassrls`
- can `{set [local]|reset} session_replication_role`
Currently, these privileges are not inheritable.

feat: `privileged_role`

---

src/supautils.c
test/expected/privileged_role.out
test/sql/privileged_role.sql

Support https://github.com/supabase/supautils/pull/33#discussion_r1007557944
needed for setting `pgaudit.*` which we usually want to persist across sessions
leaving out support for `alter database ... set ...` for now since that might affect reserved roles (since it changes the default for all roles)

feat: support `privileged_role_allowed_configs` on `alter role set`

---

.gitignore

Hi,
When building supautils with PostgreSQL 16dev on my MacOS,
I found that supautils.dylib was created but there was no entry for
.dylib in .gitignore. So, how about adding *.dylib into .gitignore,
like .gitignore in PostgreSQL also has?
Regards,

Add .dylib into .gitignore.

---

.github/workflows/main.yml
shell.nix
src/supautils.c
src/utils.c
src/utils.h
test/expected/privileged_role.out
test/fixtures.sql
test/sql/privileged_role.sql

Allows using the `supautils.privileged_role` to do:
- `alter role anon set statement_timeout = '15s'` ([ref](https://github.com/supabase/supabase/discussions/9314#discussioncomment-4352758)) - c8efcd7061e062f1b3d46f1f1a41aa48a66f4c68
- `grant testme to authenticator`([ref](https://github.com/supabase/supabase/discussions/9314#discussioncomment-4616722), also affects [custom db roles](https://github.com/supabase/supabase/discussions/11948#discussioncomment-4802137)) - b3a6e95cc070abd3b368e9dd4144e4eae9eff05d
Allows using wildcards on placeholders defined on `privileged_role_allowed_configs = "pgrst.*"`, this solves:
- `alter role authenticator set pgrst.db_plan_enabled to true`([ref](https://github.com/supabase/supabase/discussions/9314#discussioncomment-4469017)) - …

Security patch fixes

---

src/supautils.c

With the setting supautils.privileged_role not set, supautils caused a segmentation fault when CREATE ROLE command was executed. ISTM that this happened because supautils_hook() unexpectedly passed "privileged_role" variable to get_role_oid() even though it's NULL. Attached patch fixes this bug.

Fix bug that could cause supautils to lead to segmentation fault.

---

src/supautils.c
test/expected/privileged_role.out
test/fixtures.sql
test/sql/privileged_role.sql

Feature
Only one role can be a privileged role, because the privilege checks use equality (`current_role == supautils.privileged_role`)
Privilege checks use membership checks (`is_member_of_role(current_role, supautils.privileged_role`), so multiple roles can be privileged

feat: make privilege role inheritable

---

nix/pg_tle.nix
shell.nix
src/privileged_extensions.c
test/expected/privileged_extensions.out
test/sql/privileged_extensions.sql

feature
Only per-extension `before-create` & `after-create` custom scripts are supported
Support global `before-create` custom script. Execution order is:
- `before-create.sql`
- `$ext/before-create.sql`
- `CREATE EXTENSION`
- `$ext/after-create.sql`
Also support interpolating `@extname`, `@extschema@`, `@extversion@`, `@extcascade@` in extension custom scripts.
This is needed for cascade-creating TLEs that require privileged extensions, e.g.:
```sql
select pgtle.install_extension('foo', '1', '', 'select 1', array['vector']);
create extension foo cascade;
```
In this case we can use something like this as `before-create.sql`:
<details>
<summary>before-create.sql</summary>
```sql
-- Suppress NOTICEs along the lines of "extension already exists"
set client_min_messages = warning;
set …
```

feat: global before-create extension custom script

---

shell.nix
src/supautils.c
test/expected/privileged_role.out
test/fixtures.sql
test/sql/privileged_role.sql

Feature
privileged_role can't manage `ALL TABLES` or `TABLES IN SCHEMA` (PG15+) publications
privileged_role can `create publication p for all tables`, `alter publication p add tables in schema public`, etc.

feat: allow privileged_role to create ALL TABLES publication

---

Makefile
README.md
shell.nix
src/constrained_extensions.c
src/constrained_extensions.h
src/supautils.c
supautils.control
test/expected/constrained_extensions.out
test/expected/constrained_extensions_1.out
test/sql/constrained_extensions.sql

[Rendered documentation](https://github.com/steve-chavez/supautils/blob/constrained-exts/README.md#constrained-extensions)
Define a setting:
```sql
supautils.constrained_extensions = '{"plrust": {"cpu": 16, "mem": "1GB", "disk": "500MB"}, {"anotherone": { "cpu":64}}'
```
And extensions that don't comply the minimum resources will fail:
```sql
create extension plrust;
ERROR:  not enough resources for using this extension
```

feat: constrained extensions

---

.github/workflows/main.yml
.gitignore
Makefile
nix/pgScript.nix
nix/supautils.nix
shell.nix
src/constrained_extensions.c
src/supautils.c
src/utils.h
test/expected/constrained_extensions.out
test/expected/constrained_extensions_1.out
test/sql/constrained_extensions.sql

Passes a make flag so `supautils.constrained_extensions` goes from `PGC_SIGHUP` context (only editable in config file) to `PGC_USERSET` (editable in SQL). This way the json validation can be tested in regular `.sql/.out` tests.
* Adds tests for `supautils.constrained_extensions` json validation.
* Also a fix for wrong json scalar when expecting object

test: constrained_extensions valid json config 

---

README.md

And it doesn't require any database object. This is so it's easy to upgrade the extension and doesn't expose details to the user.
[Related discussion](https://supabase.slack.com/archives/C01D6TWFFFW/p1701142838705499?thread_ts=1701092064.580629&cid=C01D6TWFFFW) (internal slack thread)

readme: clarify that it's only a shared library

---

nix/withTmpDb.sh.in
shell.nix
src/privileged_extensions.c
src/supautils.c
src/utils.c
src/utils.h
test/expected/privileged_extensions.out
test/sql/privileged_extensions.sql

This caused an issue here: https://github.com/supabase/postgres/actions/runs/7551764226/job/20561373521#step:15:4305
TODO:

fix: prevent nested `switch_to_superuser()` from corrupting `prev_role_*`

---

Makefile
src/constrained_extensions.c

can't compile on macos otherwise

fix: disable sysinfo checks on macos

---

.github/workflows/release.yml
Makefile
README.md
nix/pg_cron.nix
nix/withTmpDb.sh.in
shell.nix
src/extensions_parameter_overrides.c
src/extensions_parameter_overrides.h
src/privileged_extensions.c
src/privileged_extensions.h
src/supautils.c
test/expected/privileged_extensions.out
test/sql/privileged_extensions.sql

Allows overriding `create extension` parameters. E.g. with:
```
supautils.extensions_parameter_overrides = '{"pg_cron":{"schema":"pg_catalog"}}'
```
When someone runs `create extension pg_cron with schema public`, it gets created in `pg_catalog` instead:
```
postgres=> \dx
List of installed extensions
Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
pg_cron | 1.5     | pg_catalog | Job scheduler for PostgreSQL
plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
```
Currently only supports `schema`, but may support `version`, `owner`, etc. in the future.

feat: extensions parameter overrides

---

.github/workflows/main.yml
.github/workflows/release.yml
Makefile
README.md
nix/withTmpDb.sh.in
src/drop_trigger_grants.c
src/drop_trigger_grants.h
src/supautils.c
test/expected/privileged_role.out
test/sql/privileged_role.sql

feature
The `TRIGGER` table privilege is inconsistent in that it allows roles to create triggers on tables, but doesn't allow them to drop said triggers. This prevents use cases such as allowing users to manage triggers on `auth.users`, `realtime.messages`, etc. without giving them table ownership.
The new config `supautils.drop_trigger_grants` achieves this in a similar fashion to https://github.com/supabase/supautils/pull/85

feat: dropping table triggers w/o being owners

---

.github/workflows/main.yml
.gitignore
README.md
nix/postgresql/17.nix
nix/postgresql/default.nix
nix/postgresql/generic.nix
nix/postgresql/patches/less-is-more.patch
nix/postgresql/patches/locale-binary-path.patch
nix/postgresql/patches/paths-for-split-outputs.patch
nix/postgresql/patches/paths-with-postgresql-suffix.patch
nix/postgresql/patches/relative-to-symlinks-16+.patch
nix/postgresql/patches/relative-to-symlinks.patch
nix/postgresql/patches/socketdir-in-run-13+.patch
nix/postgresql/patches/socketdir-in-run.patch
nix/postgresql/patches/specify_pkglibdir_at_runtime.patch
nix/postgresql/pg_config.sh
shell.nix
src/constrained_extensions.c
src/drop_trigger_grants.c
src/extensions_parameter_overrides.c
src/policy_grants.c
src/utils.h

In pg 17, `makeJsonLexContextCstringLen` changed its signature.
From:
```c
JsonLexContext * makeJsonLexContextCstringLen(const char *json, size_t len, int encoding, bool need_escapes)
```
To:
```c
JsonLexContext * makeJsonLexContextCstringLen(JsonLexContext *lex, const char *json, size_t len, int encoding, bool need_escapes)
```

feat: compatibility with pg 17

---

Makefile
nix/withTmpDb.sh.in
src/privileged_extensions.c
src/privileged_extensions.h
src/supautils.c
test/expected/privileged_extensions.out
test/fixtures.sql
test/sql/privileged_extensions.sql

Current logic doesn't capture the `ALTER EXTENSION .. SET SCHEMA` statement.
This uses the `pageinspect` contrib extension for testing.
Closes https://github.com/supabase/supautils/issues/88.

feat: allow changing extension schema

---

README.md
src/privileged_extensions.c
src/privileged_extensions.h
src/supautils.c
src/utils.c
src/utils.h
test/expected/privileged_extensions.out
test/sql/privileged_extensions.sql

Acts the same as the `supautils.privileged_extensions_superuser` GUC, this is still maintained for backwards compatibility.
Also renames variables to clarify the codebase.
Related to the discussion on https://github.com/supabase/supautils/issues/67#issuecomment-2472436837

feat: add supautils.superuser GUC

---

src/supautils.c
test/expected/privileged_extensions.out
test/fixtures.sql
test/sql/privileged_extensions.sql

This bug was introduced by fcb20b39de2c56f066ac68066ffa4ea870d92d1a (https://github.com/supabase/supautils/pull/94)
Looks like it escaped review because of https://github.com/supabase/supautils/issues/79.

fix: not allowing to alter schema on non-extension

---

src/pg_prelude.h
src/supautils.c
src/utils.h
test/expected/event_triggers.out
test/sql/event_triggers.sql

Closes https://github.com/supabase/supautils/issues/67.
The `privileged_role` is able to switch to superuser to create event triggers.
To prevent privesc, superusers and `reserved_roles` skip event trigger execution.
Limitation: while doing `create extension` event triggers will not be fired, since extensions are created by a superuser.
It uses the `fmgr_hook` to skip event triggers. However note that `fmgr_hook` doesn't really offer a direct way to say "skip this function execution" (although we can abort with `ereport`), so to achieve this the workaround is to override the `FmgrInfo` and turn into a noop.

feat: support non-superuser event trigger

---

src/supautils.c
test/expected/event_triggers.out
test/sql/event_triggers.sql

Currently this poses a problem when doing `create extension` as it will log a lot of warnings:
```
create extension postgres_fdw;
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
WARNING:  Skipping event trigger
```
And this will cause false alarm on users. The same problem will also
happen on big migration scripts ran by any role in `supautils.reserved_roles`.
Changing it to NOTICE would also have a similar effect. …

correct: do not log skipped event triggers

---

Makefile
src/supautils.c
src/utils.c
src/utils.h

This will avoid duplicating code for event triggers, see https://github.com/supabase/supautils/pull/106#issuecomment-2639131683.
* Adds a reusable `alter_owner` function.
* Avoids dynamic allocation and instead uses stack allocation for the generated sql.

refac: encapsulate owner change logic

---

src/supautils.c
src/utils.c
src/utils.h
test/expected/event_triggers.out.in
test/sql/event_triggers.sql

Continues the work on https://github.com/supabase/supautils/pull/98, it only allowed CREATE. Now we allow ALTER and DROP:
```sql
set role privileged_role;
alter event trigger event_trigger_1 disable;
drop event trigger event_trigger_1;
```

Allow ALTER and DROP event trigger

---

test/expected/event_triggers.out.in
test/expected/reserved_roles.out
test/fixtures.sql
test/sql/event_triggers.sql
test/sql/reserved_roles.sql

Starting from pg16 not every role can create objects on the public schema by default, this is troublesome for tests that need to create objects using any role since in each test file we need to `grant` explicit privileges.
Instead we make grant these privileges globally on `test/fixtures.sql`:
```sql
grant all on schema public to privileged_role;
grant all on schema public to rolecreator;
grant all on schema public to supabase_storage_admin;
```

test: make schema public create compat on pg >= 16

---

Makefile
src/event_triggers.c
src/event_triggers.h
src/pg_prelude.h
src/supautils.c
test/expected/event_triggers.out.in
test/expected/event_triggers_super.out
test/sql/event_triggers.sql
test/sql/event_triggers_super.sql

Closes https://github.com/supabase/supautils/issues/110.
superuser evtrigs now work as usual with the exception of `CREATE EXTENSION`. Which will now fire superuser evtrigs, but not regular user evtrigs.
This is because how `CREATE EXTENSION` works under supautils (switchs to superuser before executing CREATE EXTENSION).

feat: execute event triggers under superuser

---

README.md

Closes https://github.com/supabase/supautils/issues/116.
[Rendered](https://github.com/steve-chavez/supautils/blob/fix-docs/README.md)
Note that documenting the privileged role is required for documenting  event triggers https://github.com/supabase/supautils/pull/115
Also reorganizes the docs and renames some features for easier understanding.

Document privileged role

---

nix/withTmpDb.sh.in
test/init.conf

Setting GUCs inside the bash file is complicated and is not easy to read.
Use the `include 'init.conf` directive for simplifying the config file.
It will also replace `@TMPDIR@` inside the config file.

chore: simplfy config for tmp db

---

src/event_triggers.c
src/supautils.c

Previous [fix](https://github.com/supabase/supautils/pull/129) could override an existing function.

fix: evtrigs use existing version function as noop

---

README.md
src/supautils.c
test/expected/event_triggers.out.in
test/sql/event_triggers.sql

Adds a boolean `supautils.log_skipped_evtrigs` GUC, false by default.
This will log skipped evtrigs with a NOTICE level like:
```sql
set role postgres;
set supautils.log_skipped_evtrigs = true;
create table supa_stuff();
NOTICE:  Skipping event trigger function "show_current_user" for user "postgres"
NOTICE:  Skipping event trigger function "become_super" for user "postgres"
```

feat: log skipped event triggers when enabled

---

src/supautils.c
test/expected/event_triggers.out.in
test/sql/event_triggers.sql

There's not enough explanation on the cause of the skipped event triggers when `supautils.log_skipped_evtrigs` is enabled.
Now logs will show the extra DETAIL to solve this:
```sql
create table supa_stuff();
NOTICE:  Skipping event trigger function "show_current_user" for user "postgres"
DETAIL:  "postgres" is a superuser and the function "show_current_user" is not superuser-owned, it's owned by "privileged_role"
```

feat: log more detail on skipped event triggers

---

Makefile
README.md
nix/pgmq.nix
shell.nix
src/event_triggers.c
src/event_triggers.h
src/supautils.c
test/expected/eq15_pgmq.out
test/sql/eq15_pgmq.sql

Under the following conditions:
- plpgsql_check is enabled (can be any other extension that uses the `fmgr_hook`).
+ This means that the `supautils_needs_fmgr_hook` returns true anyway.
- After doing `create extension`, function owners are downgraded from superuser to non-super.
Supautils event trigger skipping mechanism will wrongly intercept the downgraded functions and force a noop (internally it's the `version()` function) causing the extension to misbehave.
The `pgmq` extension is used to test this failure. This error is proven by CI ([logs](https://github.com/supabase/supautils/actions/runs/14408928229/job/40412071125?pr=134)):
```
select
pgmq.create('Foo');
+NOTICE:  Skipping event trigger function "create" for user "postgres"
+DETAIL:  "postgres" is a superuser and the function …
```

fix: evtrig detection under another extension fmgr_hook

---

test/expected/event_triggers.out.in
test/expected/event_triggers_super.out
test/sql/event_triggers.sql
test/sql/event_triggers_super.sql

skipped event triggers in tests are easier to read this way.

test: use supautils.log_skipped_evtrigs for evtrig tests

---

src/privileged_extensions.c
src/privileged_extensions.h
src/supautils.c

Partly addresses https://github.com/supabase/supautils/issues/79
The `handle_alter_extension` and `handle_drop_extension` were using `run_process_utility_hook` various times unnecessarily.
Now this operation is clearly executed only once on each statement case.

refactor: rm run_process_utility_hook from internal module

---

src/privileged_extensions.c
src/privileged_extensions.h
src/supautils.c

The `handle_create_extension` function repeated statements unnecessarily:
- switched to superuser multiple times
- downgraded to privileged role multiple times
The switching only needed to be done one time at the start, and downgrading one time at the end.
The same effect is maintained, no tests are broken.
Also `run_process_utility_hook` is now executed once for the `create extension` logic.
Partly addresses https://github.com/supabase/supautils/issues/79.

refactor: deduplicate logic in create extension

---

src/pg_prelude.h
src/supautils.c
src/utils.c
src/utils.h
test/expected/event_triggers.out.in
test/expected/event_triggers_super.out
test/sql/event_triggers.sql
test/sql/event_triggers_super.sql

The code is shorter and there's less room for error.
Also tests that evtrigs don't fire for all the non-superuser fdws and publications.

refactor: use C APIs on alter_owner instead of SPI 

---

.github/workflows/release.yml
test/expected/extension_custom_scripts.out
test/init.conf.in
test/init.sh
test/init.sql
test/sql/extension_custom_scripts.sql

Follow up to https://github.com/supabase/supautils/pull/147
Assert extension custom scripts are run for extensions not in `supautils.privileged_extensions`

test: custom scripts on non-privileged extension
